<?php
/**
 * @file
 * Code for the country_taxonomy feature.
 */

include_once 'country_taxonomy.features.inc';

function country_taxonomy_post_features_rebuild($component) {
  if ($voc = taxonomy_vocabulary_machine_name_load('countries')) {
    $base_path = drupal_get_path('module', 'country_taxonomy');
    $json = json_decode(
      file_get_contents(
        $base_path . '/data/countries.json'
      )
    );
    if (!empty($json)) {
      foreach ($json as $row) {
        $q = db_select('field_data_field_iso_code', 'a');
        $q->fields('a', array('entity_id'));
        $q->condition('entity_type', 'taxonomy_term');
        $q->condition('bundle', 'countries');
        $q->condition('field_iso_code_value', $row->code2l);
        if ($tid = $q->execute()->fetchField()) {
          $term = taxonomy_term_load($tid);
        }
        else {
          $term = new stdClass();
          $term->language = 'en';
        }
        $term->name = $row->name;
        $term->name_field['en'][0]['value'] = $row->name;
        $term->field_official_name['en'][0]['value'] = $row->name_official;
        $term->field_iso_code[LANGUAGE_NONE][0]['value'] = strtoupper($row->code2l);
        $term->field_iso3l_code[LANGUAGE_NONE][0]['value'] = strtoupper($row->code3l);
        $term->vid = $voc->vid;

        if (empty($term->field_image)) {
          $dest_path = file_default_scheme() . '://images/flags';
          if (file_prepare_directory($dest_path, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS) === FALSE) {
            $dest_path = NULL;
            PTK::log_warning('Cannot prepare destination directory: ' . $dest_path);
          }
          $source_image = realpath($base_path . sprintf('/data/flags/flag-%s.png', strtolower($row->code2l)));
          $destination = $dest_path . '/' . basename($source_image);
          if ($dest_path && file_exists($source_image)) {
            $file = (object) array(
              'uid' => 1,
              'filename' => basename($source_image),
              'uri' => $source_image,
              'filemime' => file_get_mimetype($source_image),
              'status' => FILE_STATUS_PERMANENT,
            );
            if ($file_ob = file_copy($file, $destination, FILE_EXISTS_REPLACE)) {
              $term->field_image[LANGUAGE_NONE][0]['fid'] = $file_ob->fid;
            }
            else {
              PTK::log_warning('Could not copy image file: ' . $source_image . ' => ' . $destination);
            }
          }
        }
        taxonomy_term_save($term);
      }
    }
  }
}


/**
 * Implements hook_field_formatter_info().
 */
function country_taxonomy_field_formatter_info() {
  return array(
    'country_taxonomy_flag_formatter' => array(
      'label' => t('Country flag'),
      'field types' => array('taxonomy_term_reference'), //This will only be available to text fields
      'settings'  => array(
        'image_style' => 'thumbnail',
      ),
    ),
  );
}


/**
 * Implements hook_field_formatter_settings_form().
 */
function country_taxonomy_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();
  $element['image_style'] = array(
    '#type'           => 'select',
    '#title'          => t('Image style'),
    '#description'    => t('Select image style to apply'),
    '#default_value'  => $settings['image_style'],
    '#options'        => array('thumbnail'  => 'Thumbnail'),
  );
  if ($styles = image_styles()) {
    $element['image_style']['#options'] = array();
    foreach ($styles as $machine_name => $info) {
      $element['image_style']['#options'][$machine_name] = $info['label'];
    }
  }
  return $element;
}


/**
 * Implements hook_field_formatter_settings_summary().
 */
function country_taxonomy_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = t('Show the country flag using the <strong>@image_style</strong> image style', array(
    '@image_style'     => check_plain($settings['image_style']),
  ));
  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function country_taxonomy_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  foreach ($items as $delta => $meta) {
    try {
      $w = entity_metadata_wrapper('taxonomy_term', $meta['tid']);
      $image = $w->field_image->value();
      $element[$delta] = array(
        '#theme' => 'image_style',
        '#style_name' => $display['settings']['image_style'],
        '#path' => $image['uri'],
        '#attributes' => array(
          'title' => $w->label(),
          'alt' => t('Flag of @country', array('@country' => $w->label()))
        )
      );
    } catch (Exception $e) {
      watchdog_exception('country_taxonomy', $e, 'country_taxonomy_flag_formatter: Cannot load metadata for taxonomy term: ' . $meta['tid']);
    }
  }
  return $element;
}
