# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
  - config/**/*
  - docroot/core/**/*
  - docroot/modules/contrib/**/*
  - docroot/themes/bootstrap/**/*
  - docroot/vendor/**/*
  - patches/**/*
  - reports/**/*
