<?php

/**
 * Retrieve the list of countries as entities.
 *
 * @return array
 *     Array of Term entities
 */
function country_taxonomy_load_multiple() {
  $ret = array();
  /** @var \Drupal\taxonomy\TermStorageInterface $ts */
  $ts = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  $terms = $ts->loadTree('country');
  /** @var stdClass $tob */
  foreach ($terms as $tob) {
    $ret[] = $tob->tid;
  }
  return $ts->loadMultiple($ret);
}


/**
 * Retrieve a country by ISO 2-letter or 3-letter code
 *
 * @param $iso
 * @return \Drupal\taxonomy\Entity\Term
 */
function country_taxonomy_load_by_iso($iso) {
  $ret = NULL;
  $q = \Drupal\Core\Database\Database::getConnection()->select('taxonomy_term__field_country_iso2');
  $q->fields(NULL, array('entity_id'));
  $q->condition('field_country_iso2_value', $iso);
  if ($tid = $q->execute()->fetchField()) {
    $ret = \Drupal\taxonomy\Entity\Term::load($tid);
  }
  else {
    $q = \Drupal\Core\Database\Database::getConnection()->select('taxonomy_term__field_country_iso3');
    $q->fields(NULL, array('entity_id'));
    $q->condition('field_country_iso3_value', $iso);
    if ($tid = $q->execute()->fetchField()) {
      $ret = \Drupal\taxonomy\Entity\Term::load($tid);
    }
  }
  return $ret;
}


/**
 * Retrieve an array of countries for use on select form elements.
 *
 * @param string $key
 *    The array will be keyed by this field. Possible values: iso2 or iso3
 *
 * @return array
 *     Array of strings
 */
function country_taxonomy_get_countries_as_options($key = 'iso2') {
  $ret = array();
  if (!in_array(strtolower($key), array('iso2', 'iso3'))) {
    return $ret;
  }
  $field = 'field_country_' . $key;
  $terms = country_taxonomy_load_multiple();
  foreach ($terms as $term) {
    try {
      $k = $term->{$field}->getValue();
      if (!empty($k[0]['value'])) {
        $key = $k[0]['value'];
        $ret[$key] = $term->label();
      }
    } catch (\Exception $e) {  }
  }
  return $ret;
}
