<?php

/**
 * Implements Elysia hook_cronapi().
 */
function chm_service_document_cronapi() {
  return array(
    'chm_service_document_cron' => array(
      'description' => 'Import Document from chm.cbd.int',
      'rule' => '0 0 * * *',
    ),
  );
}

/**
 * Implements hook_cron().
 */
function chm_service_document_cron() {
  module_load_include('inc', 'migrate_ui', 'migrate_ui.pages');
  $machine_name = 'chm_document';
  // Update Focal Point Migration.
  $migration = Migration::getInstance($machine_name);
  
  $migration->prepareUpdate();
  watchdog('chm_service_document', 'Starting import @migration',
    array('@migration' => $machine_name), WATCHDOG_INFO);

  $result = $migration->processImport(array('update' => TRUE));

  watchdog('chm_service_document', 'Done @migration with result: @result',
    array('@migration' => $machine_name, '@result' => $result), WATCHDOG_INFO);
  return '';
}

/**
 * Implements hook_migrate_api().
 */
function chm_service_document_migrate_api() {
  return [
    'api' => 2,
    'groups' => [
      'chm-document' => [ 'title' => t('CHM Document API migrations'), ],
    ],
    'migrations' => [
      'chm_document' => [
        'class_name' => 'CHMServiceDocumentNBSAPMigration',
        'group_name' => 'chm-document',
        'urlPattern' => 'https://chm.cbd.int/api/v2013/index/select?q=realm_ss:chm+AND+schema_s:nationalReport+AND+reportType_s:B0EBAE91-9581-4BB2-9C02-52FCF9D82721',
      ],
    ],
  ];
}
