<?php
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 *
 * @inheritdoc
 */
function ptk_base_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  module_load_include('module', 'country_taxonomy');
  if ($form_id == 'system_site_information_settings') {
    $iso = NULL;
    if ($country = \Drupal::service('chm.ptk')->getCountry()) {
      $iso = $country->field_country_iso2->getValue()[0]['value'];
    }
    $form['site_information']['chm_ptk_country'] = array(
      '#title' => t('Country'),
      '#required' => TRUE,
      '#type' => 'select',
      '#default_value' => $iso,
      '#options' => array_merge(array('' => t('-- Please select --')), country_taxonomy_get_countries_as_options()),
    );
    $form['actions']['submit']['#submit'][] = 'ptk_base_form_system_site_information_settings_submit';
  }
}

function ptk_base_form_system_site_information_settings_submit(array &$form, FormStateInterface $form_state) {
  $iso = $form_state->getValue('chm_ptk_country');
  \Drupal::service('chm.ptk')->setCountry($iso);
}
