<?php

require_once dirname(__FILE__) . '/include/PTK.php';
require_once dirname(__FILE__) . '/include/forms.inc';
require_once dirname(__FILE__) . '/include/blocks.inc';

/**
 * Implements hook_permission().
 */
function ptk_base_permission() {
  return [
    'configure portal global settings' => [
      'title' => t('Configure portal global settings'),
      'description' => t('Allow configuring global variables such as block links, social media accounts etc.')
    ]
  ];
}

/**
 * Implements hook_menu().
 */
function ptk_base_menu() {
  $items = [
    'admin/reports/system' => [
      'title' => 'System report',
      'description' => 'System configuration reports',
      'page callback' => 'ptk_base_admin_page_system_report',
      'file' => 'ptk_base.admin.inc',
      'access arguments' => ['view the administration theme'],
      'menu_name' => 'management',
      'plid' => '19',
      'type' => MENU_NORMAL_ITEM,
    ],
    'admin/reports/system/types' => [
      'title' => 'Content types structure',
      'description' => 'Overview and export structure of the entities',
      'page callback' => 'ptk_base_admin_page_content_types_overview',
      'file' => 'ptk_base.admin.inc',
      'access arguments' => ['view the administration theme'],
      'menu_name' => 'management',
      'plid' => '19',
      'type' => MENU_NORMAL_ITEM,
    ],
    'admin/reports/system/taxonomy' => [
      'title' => 'Taxonomies structure',
      'description' => 'Overview and export structure of taxoomies',
      'page callback' => 'ptk_base_admin_page_taxonomies_overview',
      'file' => 'ptk_base.admin.inc',
      'access arguments' => ['view the administration theme'],
      'menu_name' => 'management',
      'plid' => '19',
      'type' => MENU_NORMAL_ITEM,
    ],
    'admin/reports/system/types/export' => [
      'title' => 'Export content type information in MS Excel',
      'page callback' => 'ptk_base_admin_page_export_content_types_overview',
      'file' => 'ptk_base.admin.inc',
      'access arguments' => ['view the administration theme'],
      'type' => MENU_CALLBACK,
    ],
    'admin/reports/system/taxonomy/export' => [
      'title' => 'Export taxonomies information in MS Excel',
      'page callback' => 'ptk_base_admin_page_export_taxonomies_overview',
      'file' => 'ptk_base.admin.inc',
      'access arguments' => ['view the administration theme'],
      'type' => MENU_CALLBACK,
    ],
    'admin/config/portal' => [
      'title' => 'Configure your portal',
      'page callback' => 'drupal_get_form',
      'page arguments' => ['ptk_base_admin_page_configure_portal_global_settings'],
      'file' => 'ptk_base.admin.inc',
      'access arguments' => ['configure portal global settings'],
      'type' => MENU_CALLBACK,
    ],
  ];
  return $items;
}

/**
 * Implements hook_block_info().
 */
function ptk_base_block_info() {
  $blocks['chm_network_sites'] = [
    'info' => t('National CHM Training Sites'),
    'status' => TRUE,
    'region' => 'content',
    'cache' => DRUPAL_CACHE_GLOBAL,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'chm-network',
    'weight' => 1,
  ];
  $blocks['chm_footer_quick_links_root'] = [
    'info' => t('Footer quick links for root domain'),
    'status' => TRUE,
    'region' => 'footer_col_1',
    'cache' => DRUPAL_NO_CACHE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'pages' => '',
    'weight' => 1,
  ];
  $blocks['chm_footer_quick_links'] = [
    'info' => t('Footer quick links'),
    'status' => TRUE,
    'region' => 'footer_col_1',
    'cache' => DRUPAL_NO_CACHE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'pages' => '',
    'weight' => 1,
  ];
  $blocks['chm_footer_follow_us'] = [
    'info' => t('Follow Us'),
    'status' => TRUE,
    'region' => 'footer_col_4',
    'cache' => DRUPAL_NO_CACHE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'pages' => '',
    'weight' => 1,
  ];
  $blocks['chm_footer_country_links'] = [
    'info' => t('Country links'),
    'status' => TRUE,
    'region' => 'footer_col_3',
    'cache' => DRUPAL_NO_CACHE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'pages' => '',
    'weight' => 1,
  ];
  $blocks['chm_content_statistics'] = [
    'info' => t('Content Statistics'),
    'status' => TRUE,
    'region' => 'content_col2-2',
    'cache' => DRUPAL_NO_CACHE,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '<front>',
    'weight' => 1,
  ];
  return $blocks;
}


/**
 * Implements hook_schema_alter()
 */
function ptk_base_schema_alter(&$schema) {
  $column = 'title_field_value';
  $new_spec = array(
    'type' => 'varchar', 'length' => 2048, 'not null' => TRUE, 'default' => '',
  );
  $table = 'field_data_title_field';
  if (isset($schema[$table])) {
    $schema[$table]['fields'][$column] = $new_spec;
  }
  $table = 'field_revision_title_field';
  if (isset($schema[$table])) {
    $schema[$table]['fields'][$column] = $new_spec;
  }

  $column = 'name_field_value';
  $table = 'field_data_name_field';
  if (isset($schema[$table])) {
    $schema[$table]['fields'][$column] = $new_spec;
  }
  $table = 'field_revision_name_field';
  if (isset($schema[$table])) {
    $schema[$table]['fields'][$column] = $new_spec;
  }

  $table = 'node';
  $column = 'title';
  if (isset($schema[$table])) {
    $schema[$table]['fields'][$column] = $new_spec;
  }
  $table = 'node_revision';
  if (isset($schema[$table])) {
    $schema[$table]['fields'][$column] = $new_spec;
  }
}


/**
 * Implements hook_block_view().
 */
function ptk_base_block_view($delta = '') {
  return PTKBlocks::render($delta);
}


/**
 * Implements hook_field_formatter_info().
 */
function ptk_base_field_formatter_info() {
  return array(
    'event_date_formatter' => array(
      'label' => t('Flexible event date'),
      'field types' => array('date', 'datestamp', 'datetime'),
      'settings' => array(
        /* No settings for now */
      ),
    )
  );
}

function ptk_base_language_switch_links_alter(array &$links, $type, $path) {
  $node = menu_get_object();
  if ($node) {
    // Unset lang-switcher links for non-existent translations
    foreach ($links as $langcode => &$link) {
      if (!isset($node->translations->data[$langcode])) {
        unset($links[$langcode]);
      }
      $link['attributes']['hreflang'] = $langcode;
    }
  }
}

/**
 * Implements hook_field_formatter_view().
 *
 * @inheritdoc
 */
function ptk_base_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array(); // Initialize the var
  $settings = $display['settings']; // get the settings
  foreach ($items as $delta => $item) {
    $f = !empty($item['value']) ? strtotime($item['value']) : NULL;
    $t = !empty($item['value2']) ? strtotime($item['value2']) : NULL;
    $value = PTK::dateIntervalString($f, $t);
    $element[$delta] = array('#type' => 'item', '#markup' => $value);
  }
  return $element;
}
